#!/bin/sh
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

# 1. محاولة تحميل التعريفات (Drivers) إذا كانت modules
modprobe e1000
modprobe virtio_net

# 2. تأكتيفي أي كارتة لقاها (بزاف ديال المرات كتكون سميتها ماشي eth0)
ifconfig eth0 up || ifconfig enp0s3 up

# 3. طلب IP أوتوماتيكيا (هادي هي اللي غاتسرح الـ Ping)
udhcpc -i eth0 || udhcpc -i enp0s3

# 4. تأكيد الـ DNS
echo "nameserver 8.8.8.8" > /etc/resolv.conf
