#!/bin/sh

# 1. Mounts
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev > /dev/null 2>&1

# 2. Network
ifconfig lo 127.0.0.1 up
ifconfig eth0 up
udhcpc -i eth0

# 3. DNS
mkdir -p /etc
echo "nameserver 8.8.8.8" > /etc/resolv.conf
echo "nameserver 1.1.1.1" >> /etc/resolv.conf

# 4. Handoff to BusyBox
exec /sbin/init
